insert into Equipment(code) values('1024')
insert into Equipment(code) values('1024')
insert into Equipment(code) values('1025')
insert into Equipment(code) values('1026')
insert into Equipment(code) values('1027')